### ISSUE TITLE
create-react-app (typescript) app - not extracting proptypes

### ISSUE THREAD

**Issue by msreekm** [strothj/react-docgen-typescript-loader#17]
i tried to implement this into my existing TS react application which was built with create-react-app-typescript and the proptypes was not extracted. any suggestions?

**Comment by dominikchrastek** [comment]
Do you use `plugin` or `loader`? I had similar issue and then I switched from `plugin` to `loader` and now it works @msreekm

**Comment by strothj** [comment]
I'm closing this issue because `create-react-app-typescript` is now deprecated and I unfortunately did not have the time to get back to this issue. Sorry!

There was an example posted here for `create-react-app` which now supports TypeScript:
https://github.com/strothj/react-docgen-typescript-loader/issues/33#issuecomment-463799754
