### ISSUE TITLE
Install fail! Error: EACCES: permission denied, mkdir 

### ISSUE THREAD

**Issue by clock157** [strothj/react-docgen-typescript-loader#35]
already root user

![image](https://user-images.githubusercontent.com/4002237/51380137-fb0de600-1b4b-11e9-9039-e5c6d5a46639.png)

**Comment by clock157** [comment]
![image](https://user-images.githubusercontent.com/4002237/51388347-17b61800-1b64-11e9-9f6f-d6fec649dde6.png)
![image](https://user-images.githubusercontent.com/4002237/51388366-269cca80-1b64-11e9-845a-2172544880e2.png)

this package maybe has wrong permission.

**Comment by clock157** [comment]
![image](https://user-images.githubusercontent.com/4002237/51388809-74fe9900-1b65-11e9-95d1-6aa67e2e0cde.png)

**Comment by strothj** [comment]
Hello,

What package manager are you using?
Is this being used in some kind of container?
Can you provide some specifics about your environment?

I believe the last publish was performed from Windows where file permissions don't map to those from posix. In any case I don't believe that should be the issue.

There being a node_modules directory with the same permissions issue is suspicious because I don't think that was published with the package.

**Comment by strothj** [comment]
That utility appears to manage the installations of node packages using a separate algorithm/method than managers like NPM or Yarn.

I don't have any issue performing a republish. I'll make a publish hopefully sometime Sunday to hopefully fix your issue.

In the mean time, perhaps you can perform a chmod/chown post dependency step.

**Comment by clock157** [comment]
I appreciate you help!

**Comment by clock157** [comment]
hi, @strothj, the issue maybe has been fixed, because of it throw another error now, it's not your package's issue. i have been contacted our CI engineer to upgrade the package manager utility that try to fix all problem. 😅
![image](https://user-images.githubusercontent.com/4002237/51508736-8976b600-1e31-11e9-996a-d2e7ded3517b.png)
